app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField, RadioField,SelectField
from wtforms.validators import Required

class CommentsForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[Required()])

    

    submit = SubmitField('SUBMIT')

class PitchForm(FlaskForm):
    category_id = SelectField('Select Category', choices=[('1', 'Interview'), ('2', 'Pick Up Lines'), ('3', 'Promotion')])
    content = TextAreaField('make a pitch', validators=[Required()])
    submit = SubmitField('Create Pitch')

class UpvoteForm(FlaskForm):
    '''
    Class to create a wtf form for upvoting a pitch
    '''
    submit = SubmitField('Upvote')

class DownvoteForm(FlaskForm):
    '''
    Class to create a wtf form for downvoting a pitch
    '''  
    submit = SubmitField('Downvote')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('What about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required
from .forms import CommentsForm ,UpdateProfile, PitchForm, UpvoteForm, DownvoteForm
from ..models import User,PhotoProfile, Pitch, Comment,PitchCategory,Downvote,Upvote
from .. import db,photos
from flask_login import login_required, current_user
import markdown2 


# Views
@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home - Welcome to this side'
    pitches= Pitch.get_all_pitches()
    return render_template('index.html', title = title, pitches= pitches)

@main.route('/all')
def all():
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home - Welcome to this side'
    pitches= Pitch.get_all_pitches()

    # upvotes = Upvote.get_all_upvotes(pitch_id=Pitch.id)
    return render_template('main.html', title = title, pitches= pitches)

@main.route('/inteview/pitches/')
def interview():
    '''
    View root page function that returns the index page and its data
    '''
    pitches= Pitch.get_all_pitches()
    title = 'Home - Welcome to this side'
    return render_template('interview.html', title = title, pitches= pitches )

@main.route('/pick_up_lines/pitches/')
def pick_up_line():
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Pick Up Lines'
    pitches= Pitch.get_all_pitches()
    return render_template('pick_up_lines.html', title = title, pitches= pitches )

@main.route('/promotion/pitches/')
def promotion():
    '''
    View root page function that returns the index page and its data
    '''
    title = 'Promotion Pitches'
    pitches= Pitch.get_all_pitches()
    return render_template('promotion.html', title = title, pitches= pitches )


#  end of category root functions
@main.route('/pitch/<int:pitch_id>')
def pitch(pitch_id):
    '''
    View pitch page function that returns the pitch details page and its data
    '''
    found_pitch= Pitch.query.get(pitch_id)
    title = pitch_id
    pitch_comments = Comment.get_comments(pitch_id)
    return render_template('pitch.html',title= title ,found_pitch= found_pitch, pitch_comments= pitch_comments)


@main.route('/pitch/new/', methods = ['GET','POST'])
@login_required
def new_pitch():
    '''
    Function that creates new pitches
    '''
    form = PitchForm()
    my_upvotes = Upvote.query.filter_by(pitch_id = Pitch.id)
    if category is None:
        abort( 404 )
    if form.validate_on_submit():
        pitch= form.content.data
        category_id = form.category_id.data
        new_pitch= Pitch(pitch= pitch, category_id= category_id)
        new_pitch.save_pitch()
        return redirect(url_for('main.all'))
    return render_template('new_pitch.html', new_pitch_form= form, category= category)

@main.route('/category/<int:id>')
def category(id):
    '''
    function that returns pitches based on the entered category id
    '''
    category = PitchCategory.query.get(id)
    if category is None:
        abort(404)
    pitches_in_category = Pitch.get_pitch(id)
    return render_template('category.html' ,category= category, pitches= pitches_in_category)

@main.route('/pitch/comments/new/<int:id>',methods = ['GET','POST'])
@login_required
def new_comment(id):
    form = CommentsForm()
    vote_form = UpvoteForm()
    if form.validate_on_submit():
        new_comment = Comment(pitch_id =id,comment=form.comment.data,username=current_user.username)
        new_comment.save_comments()
        return redirect(url_for('main.all'))
    return render_template('new_comment.html',comment_form=form, vote_form= vote_form)




@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():

        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        user_photo = PhotoProfile(pic_path = path,user = user)
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route('/view/comment/<int:id>')
def view_comments(id):
    '''
    Function that returs  the comments belonging to a particular pitch
    '''
    comments = Comment.get_comments(id)
    return render_template('view_comments.html',comments = comments, id=id)


@main.route('/test/<int:id>')
def test(id):
    '''
    this is route for basic testing
    '''
    pitch =Pitch.query.filter_by(id=1).first()
    return render_template('test.html',pitch= pitch)

@main.route('/pitch/upvote/<int:pitch_id>/upvote', methods = ['GET', 'POST'])
@login_required
def upvote(pitch_id):
    pitch = Pitch.query.get(pitch_id)
    user = current_user
    pitch_upvotes = Upvote.query.filter_by(pitch_id= pitch_id)
    if Upvote.query.filter(Upvote.user_id==user.id,Upvote.pitch_id==pitch_id).first():
        return  redirect(url_for('main.all'))
    new_upvote = Upvote(pitch_id=pitch_id, user = current_user)
    new_upvote.save_votes()
    return redirect(url_for('main.all'))
    

@main.route('/pitch/downvote/<int:pitch_id>/downvote', methods = ['GET', 'POST'])
@login_required
def downvote(pitch_id):
    pitch = Pitch.query.get(pitch_id)
    user = current_user
    pitch_downvotes = Downvote.query.filter_by(pitch_id= pitch_id)
    if Downvote.query.filter(Downvote.user_id==user.id,Downvote.pitch_id==pitch_id).first():
        return  redirect(url_for('main.all'))
    new_downvote = Downvote(pitch_id=pitch_id, user = current_user)
    new_downvote.save_votes()
    return redirect(url_for('main.all'))

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}


{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/category.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}
{% block content %}

<h3 class="text-center">{{category.name|upper}} PITCH</h3>
<hr>

{% if pitches %}
{% for pitch in pitches %}
<h3>{{pitch.id}}</h3>
{%else%}

app/templates/comment.html
{% extends 'base.html' %}
{% block content%}

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4">
      <img src="{{comment.image_path}}" class="img-responsive">
    </div>

    <div class="col-sm-8">
      {{format_comment|safe}}
    </div>
    
  </div>
</div>

{%endblock%}

app/templates/fourOwfour.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}


{%block styles %}
  {{super()}}
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{url_for('static',filename='css/all.css')}}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Lobster&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">

{% endblock %}

{% block content%}

<div
    style="background-image: url(../static/88e5913958fcccf00c0a545e66488468.jpg); background-repeat: no-repeat; background-size: cover; height:88.9vh;">

    <div class="container-fluid" style="text-align:center; padding-top:250px;">
        <h2 style="color: black;font-family: 'Anton', sans-serif;
        font-family: 'Lobster', cursive; font-size: 30px;">In life, you only have 60 seconds to impress someone. <br>
            minute can make or break you. How do we make sure that you use your 1 minute to actually say something
            meaningful?</h2>
        <p style="font-size: 20px; color: blue;">You can produce a pitch of your own choice , comment on any pitch you
            like, <br>and upvote or downvote.</p>
        <h5 style="font-size: 25px; color:blue;"> Kindly Sign in to access the opportunity.</h5> <br> <br>

        {% if current_user.is_anonymous%}
        <li class="btn btn-info" style="font-size: 20px;"><a href="{{url_for('auth.login')}}"
                class="text-light"><strong>Sign In</strong></a></li>
        {%endif%}
        </ul>

    </div>
    <div>
    <p style="font-size: 18px; color:black; text-align: center;font-family: 'Bangers', cursive; margin-top: 120px;"
    >Reserved by @2020-A-Minute-Pitch</p>
    </div>
</div>



{% endblock %}

app/templates/interview.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/interview.css')}}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock %}

{% block content %}

<section class="">
        <div class="container">
                <h3 class="text-center" style="font-size: 30px; font-weight: bolder; font-family: 'Anton', sans-serif;
                font-family: 'Lobster', cursive;
                font-family: 'Ultra', serif; color: black;">Inteview Pitches</h3>
                <a style="font-size: 20px; font-family: 'Courier New', Courier, monospace;" class="btn btn-success" href="{{url_for('main.new_pitch')}}">
                    <br>
                    Add a new Pitch
                </a>
                <hr>
                    {{macro.displayPitchesInCategories(pitches,1)}}
                <hr>
            </div>
</section>

{% endblock %}

app/templates/macros.html
{% macro displayPitches(pitches_list) %}
    {% for pitch in pitches_list[::-1] %}

      <div class="panel"style="padding:10px; text-align:center;">
          <h3 style="font-size: 20px;">{{pitch.pitch}}</h3>
          <p style="font-size: 20px;"> Posted on:{{ pitch.date.strftime('%y-%m-%d') }}</p>
          <br>
          <a href="{{url_for('main.new_comment',id=pitch.id)}}" class="btn btn-info">Add a Comment</a>
          <a style="font-size: 20px;" href="{{url_for('main.upvote',pitch_id = pitch.id)}}" class= "btn btn-success btn-sm">Upvote <span>{{pitch.upvotes.count()}}</span></a>
          <a style="font-size: 20px;" href="{{url_for('main.downvote',pitch_id = pitch.id)}}" class= "btn btn-info btn-sm">Downvote <span>{{pitch.downvotes.count()}}</span></a>&nbsp;&nbsp;|
          <a style="font-size: 20px;" href="{{url_for('main.view_comments',id=pitch.id)}}" class="btn btn-success">View Comments</a>&nbsp;&nbsp;|
         
      </div>
    {% endfor %}
{% endmacro %}

{% macro displayComments(list_of_comments) %}
{% for comment in list_of_comments[::-1]  %}

<div class="row">
          <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">
            <h4>Author</h4>
            <p>{{comment.user.username}}</p>
          </div>
          <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8">
            <h2> <a href="{{url_for('main.single_comment',id=comment.id)}}">{{comment.pitch_title}}</a> </h2>
          </div>
        </div>

{% endfor %}
{% endmacro %}
{% macro displayPitchesInCategories(pitches,id)%}
  {% for pitch in pitches[::-1] %}
  
    {% if pitch.category_id==id%}

        <div class="panel bg-light text-center style="style="box-shadow: 5px 5px 5px 5px #F2F2F2; padding:10px;">
            <p style="font-size: 30px;">{{pitch.pitch}}</p>
            <p style="font-size: 30px;"> Posted on:{{pitch.date}}</p>
            <a style="font-size: 20px;" href="{{url_for('main.new_comment',id=pitch.id)}}" class="btn btn-info">Add a Comment</a>
            <a style="font-size: 20px;" href="{{url_for('main.upvote',pitch_id = pitch.id)}}" class= "btn btn-success btn-sm">Upvote <span>{{pitch.upvotes.count()}}</span></a>
            <a style="font-size: 20px;" href="{{url_for('main.downvote',pitch_id = pitch.id)}}" class= "btn btn-info btn-sm">Downvote <span>{{pitch.downvotes.count()}}</span></a>&nbsp;&nbsp;|
            <a style="font-size: 20px;" href="{{url_for('main.view_comments',id=pitch.id)}}" class="btn btn-success">View Comments</a>&nbsp;&nbsp;
            
        </div>

    {% endif%}
  {% endfor %}
{% endmacro%}

app/templates/main.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}
{% block styles%}

{{ super() }}<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock %}

{% block content %}
<section class="">
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <a href="{{url_for('main.new_pitch')}}"><br>
                <span style="font-size: 30px; " class=" btn btn-success  text-light display-4">Add a new Pitch</span></a>
            </div> 
    </div>
    
        <hr>
    <div class="row ">
            <div class=" col-md-8 mx-auto bg-light all-pitches">
                    {{macro.displayPitches(pitches)}}
                 </div>
    </div>
    </div>
</section>
{% endblock%}

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content%}
    <div class="container-fluid">
        <div class="row">
            <div class="col text-center mt-4">
                    <a href="{{url_for('main.all')}}">
                            <button style="font-size: 20px;" type="button" class="btn btn-primary btn-sm" style="margin-bottom:10px;">
                                    <span class="glyphicon glyphicon-chevron-left" ></span> Back
                            </button>
                    </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mx-auto" style="font-size: 30px;">
               <p>{{wtf.quick_form(new_pitch_form)}}</p> 
            </div>
        </div>
    </div>
{% endblock %}

app/templates/pick_up_lines.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/pickup.css')}}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock %}
{% block content %}

<section class=" pick">
        <div class="container ">
                <h3 style="font-size: 30px; font-weight: 900; color: black; font-family: 'Anton', sans-serif;
                font-family: 'Lobster', cursive;
                font-family: 'Ultra', serif;" class="text-center ">Pick Up Lines</h3>
                <a style="font-size:20px;" class="btn-success"  href="{{url_for('main.new_pitch')}}">
                    <br>
                    Add a new Pitch
                </a>
                <hr class="bg-light">
                    {{macro.displayPitchesInCategories(pitches,2)}}
                <hr>
            </div>
</section>
{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
<!-- Content block -->
{% block content %}
<div class="container">
    <div class="row">
            <h3>Pitch ID:{{ found_pitch.id }}</h3>
            <p> {{ found_pitch.pitch }}</p>
            <a style="font-size: 25px;" href="/pitch/comments/new/{{found_pitch.id}}"> Comment</a>
    </div>
    <div class="row">
                    <h1 style="font-size: 20px;">Comments on this Pitch</h1>
                    <hr>
                    {% if pitch_comments %}
                        {{ macro.displayComments(pitch_comments) }}
                    {% else%}
                        <h3 class="text-center">This Pitch has no Comments </h3>
                    {% endif %}
                </div>
</div>
{% endblock %}

app/templates/promotion.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/promotion.css')}}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock %}
{% block content %}
<section class="">
        <div class="container">
                <h3 style="font-weight: 900; font-size: 30px; font-family: 'Anton', sans-serif;
                font-family: 'Lobster', cursive;
                font-family: 'Ultra', serif;" class="text-center">Promotion Pitches</h3>
                <a style="font-size: 20px;"  class="btn-success" href="{{url_for('main.new_pitch')}}">
                    <br>
                    Add a new Pitch
                </a>
                <hr>
                    {{macro.displayPitchesInCategories(pitches,3)}}
                <hr>
            </div>
</section>
{% endblock %}

app/templates/search.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block content %}

    <div class="container">
        <div class="row">
            <h3> Found {{ pitches| count }} matches </h3>
            <hr>
            <ul>
                {{ macro.displayPitches(pitches)}}
            </ul>
        </div>
    </div>
    
{% endblock %}

app/templates/view_comments.html
{% extends 'base.html'%}
{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Akronim%7CBellefair%7CJoti+One" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container">
        <a href="{{url_for('main.index')}}">
            <button type="button" class="btn btn-primary btn-sm">
                    <span class="glyphicon glyphicon-chevron-left" ></span> Back
                </button>
                <h3 style="color:black; font-size: 30px;">Comments:</h3>
        </a>
        <h6> &nbsp; &nbsp; <span style="font-weight:bolder">Found :</span>  &nbsp; <span style="font-family:Bellefair; font-size:30px;">{{ comments | count }} Comments</span></h6>
        <hr>
        {% for item in comments[::-1] %}
            <div class="panel">
                <p style="font-family:Bellefair; font-size:30px; padding:15px; text-align:center;">{{item.comment}}</p>
                <h5>&nbsp;&nbsp;Comment by: &nbsp;<span style="color:black;font-family:Bellefair; font-size:30px;">{{item.username}}</span></h5>
            </div>
            {%endfor%}
    </div>
{% endblock %}